language: node_js
sudo: required
node_js:
- '8'
git:
  submodules: false
before_install:
- openssl aes-256-cbc -K $encrypted_309cd113c23e_key -iv $encrypted_309cd113c23e_iv
  -in rsagh.enc -out rsagh -d
- chmod 600 rsagh
- eval `ssh-agent -s`
- ssh-add rsagh
script:
- ls -la
- yarn --version
- yarn && export APP_NAME=${APP_NAME} && CROWDIN_API=${CROWDIN_API} yarn i18n-prepare && yarn send
after_success:
- echo "Success run to get dist"
- ls -la
branches:
  only:
  - integrate/CI
