language: node_js
node_js:
- '8'
git:
  submodules:
    false
before_install:
- openssl aes-256-cbc -K $encrypted_309cd113c23e_key -iv $encrypted_309cd113c23e_iv
  -in lucky.enc -out /tmp/lucky -d
- chmod 600 /tmp/lucky
- eval `ssh-agent -s`
- ssh-add /tmp/lucky
script:
- export APP_NAME=${APP_NAME} && CROWDIN_API=${CROWDIN_API}
- git config user.email "travis@travis-ci.org"
- git config user.name "Travis CI"
- git submodule update --init --recursive
- ls -la frontend/src/lang/messages
- cd frontend && git pull origin cronjob/localization && cd ../
- git status
# - yarn && yarn i18n-prepare
# - git status
#- chmod +x deploy.sh && sh deploy.sh
# - yarn && git submodule foreach git pull origin integrate/CI
- chmod 600 deploy.sh && bash deploy.sh ${CONST_TOKEN} 
# - git remote set-url origin https://${CONST_TOKEN}@github.com/constant-money/constant-web-i18n.git
# - git status
# - git push origin integrate/CI
# - ls -la frontend/src/lang/messages
# - yarn --version
# - yarn && export APP_NAME=${APP_NAME} && CROWDIN_API=${CROWDIN_API} yarn i18n-prepare
#   && yarn send
after_success:
- git clone -b release/master https://${CONST_TOKEN}@github.com/constant-money/constant-web-i18n.git release && cp -rf ./i18n/ release/i18n/ && cd release && git add . && git commit -m "Update Message" && git push origin release/master
  # - git remote rm origin
# - git remote add origin https://${CONST_TOKEN}@github.com/constant-money/constant-web-i18n.git
# - git fetch origin release/master && git add . && git stash && git checkout release/master && git pull origin release/master && touch abc && git add . && git 
#&& git stash pop &&  git add . && git commit -m "Update NPM" && git push origin release/master
- echo "Success run to get dist"
- ls -la
branches:
  only:
  - integrate/CI
