language: node_js
# sudo: required
node_js:
- '8'
script:
- ls -la
- yarn --version
- yarn && export APP_NAME=${APP_NAME} && CROWDIN_API=${CROWDIN_API} yarn i18n-prepare && yarn send
after_success:
- echo "Success run to get dist"
- ls -la
branches:
  only:
  - integrate/CI
